
language: python
python:
 - "2.7"
sudo: false

cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/printData

install:
    - pip install -U platformio

script:
    - platformio ci --lib="src" --project-conf=platformio.ini
